TrajectoryPlannerROS:

  holonomic_robot: false
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  sim_time: 1.0
  vx_samples: 3
  vtheta_samples: 20
  meter_scoring: true
  pdist_scale: 2.0
  gdist_scale: 0.8
  latch_xy_goal_tolerance: false
